### ISSUE TITLE
Guidelines for contributions?

### ISSUE THREAD

**Issue by joshzamor** [gabrielkrieshok/ict4d-guide#1]
This looks interesting and absolutely would have been useful when I was a PCV in Tanzania.

I might suggest that if you're looking for contributions, then this github issue is to suggest that:

- The types of desired contributions are stated a bit more clearly.  e.g. I could contribute links / information that's global health focused, though maybe that's too specific on a single subject.
- Lay out the licensing of those contributions.
- Mention the mechanism.  Is it GitHub pull requests?

**Comment by gabrielkrieshok** [comment]
Hi Josh -- and thanks!

I had sort of been compiling this on the side, not sure what to do with it -- so trying to spend a few spare hours to get it out there. I'm curious actually how you found it!

I just typed up some [contribution guidelines](https://github.com/gabrielkrieshok/ict4d-guide/blob/master/about/contributing.md) -- I still think they are a little daunting for the un-initiated, but they are a start.

I'm fairly agnostic right now on things being too specific -- I actually think global health is a big gap in what's up there -- what about an entire topic page devoted to it?

In terms of licensing, I was thinking of just attaching a standard Creative Commons attribution and share-alike license, given that it will be all documentation and links to other resources. But I'm open to other ideas if you have thoughts!

**Comment by joshzamor** [comment]
Hi Gabriel, I found it from your FaceBook post to the group Digital Peace Corps.

That contribution guide looks good.  I'm no license expert, so Creative Commons seems good to me.

On Global Health, I could take a shot at adding some links and projects that I know of and submit a PR.

Nice job btw.

**Comment by gabrielkrieshok** [comment]
Oh hey @joshzamor -- hit me up on email -- I have some updates on the project you might be interested in!
